package telas;

import banco.Acesso;
import dados.UsuarioSession;
import dados.UsuarioInfo;
import javax.swing.JOptionPane;
import banco.InfoAcesso;

public class TelaSenha extends javax.swing.JFrame {

    /**
     * Creates new form TelaSenha
     */
    private TelaPerfil perfil;
    private TelaLogin login;
    
    public TelaSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoAntiga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        campoNova = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 74, 173));
        jLabel2.setText("Senha antiga");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 260, 210, 80);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 74, 173));
        jLabel3.setText("Voltar pra tela perfil");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1180, 680, 170, 30);

        campoAntiga.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoAntiga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoAntigaKeyPressed(evt);
            }
        });
        jPanel1.add(campoAntiga);
        campoAntiga.setBounds(520, 330, 570, 60);

        jButton1.setBackground(new java.awt.Color(0, 74, 173));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1180, 500, 100, 32);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 74, 173));
        jLabel4.setText("Nova senha");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 410, 210, 80);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/olhoo.png"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1100, 503, 60, 30);

        campoNova.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jPanel1.add(campoNova);
        campoNova.setBounds(520, 480, 570, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/FAzer login (8).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Acesso acesso = new Acesso();
     UsuarioSession id = new UsuarioSession();
     int userId = id.getUserId();
     
     String senhaAntiga = campoAntiga.getText();
        String novaSenha = campoNova.getText();

        if (acesso.verificaSenhaAntiga(userId, senhaAntiga)) {
            boolean atualizou = acesso.atualizarSenha(userId, novaSenha);
            if (atualizou) {
                System.out.println("Senha atualizada com sucesso!");
                 dispose();
                 login = new TelaLogin();
                 login.setVisible(true);
                 login.setExtendedState(login.MAXIMIZED_BOTH);
            } else {
                System.out.println("Erro ao atualizar a senha.");
                }
        } else {
            System.out.println("Senha antiga incorreta.");
            JOptionPane.showMessageDialog(null, "Senha antiga incorreta", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoAntigaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAntigaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                campoNova.requestFocus(); // Foca no botão "Salvar"
            }
    }//GEN-LAST:event_campoAntigaKeyPressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    int userId = UsuarioSession.getUserId();
    System.out.println("userId: " + userId);  // Verifique o valor de userId antes de buscar no banco
    InfoAcesso infoAcesso = new InfoAcesso();
    UsuarioInfo usuarioInfo = infoAcesso.getUsuarioInfo(userId);
    
        System.out.println("usuarioInfo: " + usuarioInfo);  // Para verificar se está null

        if (usuarioInfo != null) {
        perfil = new TelaPerfil(usuarioInfo);  // Agora, usuarioInfo não é null
        perfil.setExtendedState(perfil.MAXIMIZED_BOTH);
        perfil.setLocationRelativeTo(null);
        perfil.setVisible(true);
        this.dispose();
    } else {
        System.out.println("Erro: usuarioInfo está null");
        // Aqui você pode tratar a situação, como exibir uma mensagem de erro para o usuário.
    }
    }//GEN-LAST:event_jLabel3MouseClicked

    private boolean senhaVisivel = false;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (senhaVisivel) {
            campoNova.setEchoChar('*'); // Oculta a senha
        } else {
            campoNova.setEchoChar((char) 0); // Exibe a senha
        }
        senhaVisivel = !senhaVisivel;
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoAntiga;
    private javax.swing.JPasswordField campoNova;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
