/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.table.TableModel;
import java.sql.*;
import banco.Acesso;
import banco.InfoAcesso;
import dados.UsuarioInfo;
import dados.UsuarioSession;
import java.awt.Color;
import java.awt.Font;

public class TelaUsuarios extends javax.swing.JFrame {
        
     private DefaultTableModel modeloTabela;
     private TelaPerfil perfil;
     private TelaProcurarFichasUsuarios procurar;

     public TelaUsuarios() {
        initComponents();

        configurarTabela(); 

        setVisible(true);  
    }

    // Método para configurar a tabela
    private void configurarTabela() {
        // Definindo o modelo da tabela
        String[] colunas = {"Id", "Nome", "Idade", "Telefone", "Academia"};
        modeloTabela = new DefaultTableModel(colunas, 0);
        tabelaUsuarios.setModel(modeloTabela); 
        
    tabelaUsuarios.getTableHeader().setFont(new Font("Arial", Font.BOLD, 30));
    tabelaUsuarios.getTableHeader().setForeground(Color.WHITE);  
    tabelaUsuarios.getTableHeader().setBackground(new Color(0, 74, 173)); 
        
    tabelaUsuarios.getColumnModel().getColumn(0).setPreferredWidth(20);  // ID
    tabelaUsuarios.getColumnModel().getColumn(1).setPreferredWidth(320); // Nome 
    tabelaUsuarios.getColumnModel().getColumn(2).setPreferredWidth(60);  // Idade 
    tabelaUsuarios.getColumnModel().getColumn(3).setPreferredWidth(150); // Telefone
    tabelaUsuarios.getColumnModel().getColumn(4).setPreferredWidth(200); // Academia

    tabelaUsuarios.setRowHeight(35);
        
        Acesso acesso = new Acesso();
        acesso.carregarUsuarios(modeloTabela,"");  
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        pesquisarPorNome = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        tabelaUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaUsuarios);

        jPanel1.setBackground(new java.awt.Color(0, 74, 173));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquisar nome de usuário");

        jTextFieldPesquisa.setBackground(new java.awt.Color(204, 204, 255));
        jTextFieldPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });

        pesquisarPorNome.setBackground(new java.awt.Color(0, 0, 153));
        pesquisarPorNome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        pesquisarPorNome.setForeground(new java.awt.Color(255, 255, 255));
        pesquisarPorNome.setText("Pesquisar");
        pesquisarPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarPorNomeActionPerformed(evt);
            }
        });
        pesquisarPorNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pesquisarPorNomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisarPorNomeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pesquisarPorNome)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPesquisa)
                    .addComponent(pesquisarPorNome))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelTabelaLayout = new javax.swing.GroupLayout(painelTabela);
        painelTabela.setLayout(painelTabelaLayout);
        painelTabelaLayout.setHorizontalGroup(
            painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelTabelaLayout.setVerticalGroup(
            painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTabelaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setForeground(new java.awt.Color(0, 74, 173));
        jMenu1.setText("Fichas de outros usuários");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 74, 173));
        jMenu2.setText("Voltar pra tela perfil");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
    int userId = UsuarioSession.getUserId();
    System.out.println("userId: " + userId);  // Verifique o valor de userId antes de buscar no banco
    InfoAcesso infoAcesso = new InfoAcesso();
    UsuarioInfo usuarioInfo = infoAcesso.getUsuarioInfo(userId);
    
        System.out.println("usuarioInfo: " + usuarioInfo);  // Para verificar se está null

        if (usuarioInfo != null) {
        perfil = new TelaPerfil(usuarioInfo);  // Agora, usuarioInfo não é null
        perfil.setExtendedState(perfil.MAXIMIZED_BOTH);
        perfil.setLocationRelativeTo(null);
        perfil.setVisible(true);
        this.dispose();
    } else {
        System.out.println("Erro: usuarioInfo está null");
        // Aqui você pode tratar a situação, como exibir uma mensagem de erro para o usuário.
    }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void pesquisarPorNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisarPorNomeKeyPressed
     
    }//GEN-LAST:event_pesquisarPorNomeKeyPressed

    private void pesquisarPorNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisarPorNomeKeyReleased
    
    }//GEN-LAST:event_pesquisarPorNomeKeyReleased

    private void pesquisarPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarPorNomeActionPerformed
      String nomePesquisa = jTextFieldPesquisa.getText().toLowerCase().trim();  // Obtém o texto da pesquisa e remove espaços extras
    Acesso acesso = new Acesso();
    acesso.carregarUsuarios(modeloTabela, nomePesquisa); 
    }//GEN-LAST:event_pesquisarPorNomeActionPerformed

    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                pesquisarPorNome.requestFocus(); // Foca no botão "Salvar"
            }
   
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                pesquisarPorNome.doClick(); // Executa o botão "Salvar"
            } 
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
          procurar = new TelaProcurarFichasUsuarios();
          procurar.setVisible(true);
          procurar.setExtendedState(procurar.MAXIMIZED_BOTH); 
          this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
   public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            TelaUsuarios tela = new TelaUsuarios();
            tela.setVisible(true);  // Exibe a tela
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JPanel painelTabela;
    private javax.swing.JButton pesquisarPorNome;
    private javax.swing.JTable tabelaUsuarios;
    // End of variables declaration//GEN-END:variables
}
