package telas;

import javax.swing.JOptionPane;
import banco.Acesso;
import banco.InfoAcesso;
import dados.UsuarioInfo;
import dados.UsuarioSession;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Pedro
 */
public class TelaDeletarFicha extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeletarFicha
     */
    private TelaPerfil perfil; 
    private TelaPesquisarFicha pesquisar;
    
    public TelaDeletarFicha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoExclui = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        voltaPerfil = new javax.swing.JMenuItem();
        voltaFicha = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        campoExclui.setBackground(new java.awt.Color(204, 204, 204));
        campoExclui.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoExclui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoExcluiKeyPressed(evt);
            }
        });
        jPanel1.add(campoExclui);
        campoExclui.setBounds(490, 440, 690, 50);

        jButton1.setBackground(new java.awt.Color(0, 74, 173));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1200, 460, 120, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/FAzer login (14).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 720);

        jMenu1.setForeground(new java.awt.Color(0, 74, 173));
        jMenu1.setText("Voltar");

        voltaPerfil.setText("Voltar pra tela perfil");
        voltaPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaPerfilActionPerformed(evt);
            }
        });
        jMenu1.add(voltaPerfil);

        voltaFicha.setText("Voltar pra tela de fichas");
        voltaFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaFichaActionPerformed(evt);
            }
        });
        jMenu1.add(voltaFicha);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String excluiFicha = campoExclui.getText();
    Acesso acesso = new Acesso();
    

    Object[] options = {"Sim", "Não"};
    int resposta = JOptionPane.showOptionDialog(
        null, 
        "Deseja continuar?", 
        "Confirmação", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE, 
        null, 
        options, 
        options[0]
            
    );

    if (resposta == JOptionPane.YES_OPTION) {
        if(acesso.excluirFicha(excluiFicha)) {
            System.out.println("Usuário escolheu Sim.");
            JOptionPane.showMessageDialog(null, "Ficha excluída com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            int userId = UsuarioSession.getUserId();
    System.out.println("userId: " + userId);  // Verifique o valor de userId antes de buscar no banco
    InfoAcesso infoAcesso = new InfoAcesso();
    UsuarioInfo usuarioInfo = infoAcesso.getUsuarioInfo(userId);
    
        System.out.println("usuarioInfo: " + usuarioInfo);  // Para verificar se está null

        if (usuarioInfo != null) {

        UsuarioSession id = new UsuarioSession();
        List<String> nomesFichas = infoAcesso.getNomesFichas(id); // Armazena o retorno do método em nomesFichas

        if (nomesFichas != null && !nomesFichas.isEmpty())
        {
            pesquisar = new TelaPesquisarFicha(nomesFichas);
            pesquisar.setVisible(true);
            pesquisar.setExtendedState(pesquisar.MAXIMIZED_BOTH);
            this.dispose();
        }
        this.dispose();
    } else {
        System.out.println("Erro: usuarioInfo está null");
        // Aqui você pode tratar a situação, como exibir uma mensagem de erro para o usuário.
    }

        } else {
            System.out.println("Erro ao deletar ficha");
            JOptionPane.showMessageDialog(null, "Erro ao deletar ficha", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } else if (resposta == JOptionPane.NO_OPTION) {
        System.out.println("Usuário escolheu Não.");
        campoExclui.setText("");
    } else {
        System.out.println("Usuário fechou a caixa de diálogo.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoExcluiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoExcluiKeyPressed
       if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.requestFocus(); // Foca no botão "Salvar"
            }
   
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.doClick(); // Executa o botão "Salvar"
            }   // TODO add your handling code here:
    }//GEN-LAST:event_campoExcluiKeyPressed

    private void voltaPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaPerfilActionPerformed
        int userId = UsuarioSession.getUserId();
        System.out.println("userId: " + userId);  // Verifique o valor de userId antes de buscar no banco
        InfoAcesso infoAcesso = new InfoAcesso();
        UsuarioInfo usuarioInfo = infoAcesso.getUsuarioInfo(userId);

        System.out.println("usuarioInfo: " + usuarioInfo);  // Para verificar se está null

        if (usuarioInfo != null) {
            perfil = new TelaPerfil(usuarioInfo);  // Agora, usuarioInfo não é null
            perfil.setExtendedState(perfil.MAXIMIZED_BOTH);
            perfil.setLocationRelativeTo(null);
            perfil.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Erro: usuarioInfo está null");
            // Aqui você pode tratar a situação, como exibir uma mensagem de erro para o usuário.
        }
    }//GEN-LAST:event_voltaPerfilActionPerformed

    private void voltaFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaFichaActionPerformed
        InfoAcesso acesso = new InfoAcesso();
        UsuarioSession id = new UsuarioSession();
        List<String> nomesFichas = acesso.getNomesFichas(id); // Armazena o retorno do método em nomesFichas

        if (nomesFichas != null && !nomesFichas.isEmpty())
        {
            pesquisar = new TelaPesquisarFicha(nomesFichas);
            pesquisar.setVisible(true);
            pesquisar.setExtendedState(pesquisar.MAXIMIZED_BOTH);
            this.dispose();
        }
    }//GEN-LAST:event_voltaFichaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeletarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeletarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeletarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeletarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeletarFicha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoExclui;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem voltaFicha;
    private javax.swing.JMenuItem voltaPerfil;
    // End of variables declaration//GEN-END:variables
}
