
package telas;

import banco.Acesso;
import javax.swing.JOptionPane;
import dados.UsuarioInfo;
import dados.Login;
import banco.InfoAcesso;
import dados.InfosCadastro;
import dados.Id;
import dados.UsuarioSession;

public class TelaAlterarInfos extends javax.swing.JFrame {

    private String altemail;
    private String altera;
    private TelaEditaInfo edita;
    private TelaPerfil perfil;
    private UsuarioInfo usuario;
    
    public TelaAlterarInfos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        alteraSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Digite a senha para prosseguir:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(520, 330, 550, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1030, 380, 130, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Voltar para o Perfil");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1190, 690, 170, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/olhoo.png"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(950, 390, 60, 30);

        alteraSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alteraSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alteraSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(alteraSenha);
        alteraSenha.setBounds(520, 380, 430, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/Alterar.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1355, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                  
    altera = alteraSenha.getText();
    
    Acesso acesso = new Acesso();
    UsuarioSession id = new UsuarioSession();
    
    int userId = id.getUserId();
if (acesso.acessoEdita(altera, userId) == true) {
    InfoAcesso infoAcesso = new InfoAcesso();
    System.out.println("Acesso edita - "+userId);
    UsuarioInfo usuarioInfo = infoAcesso.getUsuarioInfo(userId);

    if (usuarioInfo != null) {
        edita = new TelaEditaInfo(usuarioInfo);
        edita.recebeId(userId);
        edita.setExtendedState(edita.MAXIMIZED_BOTH);
        edita.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(null, "Erro nos dados informados", "Erro", JOptionPane.ERROR_MESSAGE);
    }
} else {
    System.out.println("Erro: userId inválido (null ou 0) após a verificação de acesso.");
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            jButton1.doClick(); // Executa o botão "Salvar"
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
           int userId = UsuarioSession.getUserId();
    System.out.println("userId: " + userId);  // Verifique o valor de userId antes de buscar no banco
    InfoAcesso infoAcesso = new InfoAcesso();
    UsuarioInfo usuarioInfo = infoAcesso.getUsuarioInfo(userId);
    
        System.out.println("usuarioInfo: " + usuarioInfo);  // Para verificar se está null

        if (usuarioInfo != null) {
        perfil = new TelaPerfil(usuarioInfo);  // Agora, usuarioInfo não é null
        perfil.setExtendedState(perfil.MAXIMIZED_BOTH);
        perfil.setLocationRelativeTo(null);
        perfil.setVisible(true);
        this.dispose();
    } else {
        System.out.println("Erro: usuarioInfo está null");
        // Aqui você pode tratar a situação, como exibir uma mensagem de erro para o usuário.
    }
    }//GEN-LAST:event_jLabel5MouseClicked

    private boolean senhaVisivel = false;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if (senhaVisivel) {
            alteraSenha.setEchoChar('*'); // Oculta a senha
        } else {
            alteraSenha.setEchoChar((char) 0); // Exibe a senha
        }
        senhaVisivel = !senhaVisivel;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void alteraSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alteraSenhaKeyPressed
 if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.requestFocus(); // Foca no botão "Salvar"
            }
   
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.doClick(); // Executa o botão "Salvar"
            }        // TODO add your handling code here:
    }//GEN-LAST:event_alteraSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarInfos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField alteraSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
