/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import banco.InfoAcesso;
import dados.UsuarioInfo;
import dados.Id;
import dados.UsuarioSession;
import javax.swing.JOptionPane;
import dados.Ficha;
import banco.CadastrarInformacoes;

/**
 *
 * @author Pedro
 */
public class TelaCriarFicha extends javax.swing.JFrame {

    /**
     * Creates new form TelaCriarFicha
     */
    private TelaModelo modelo;
    private TelaPerfil perfil;
    private UsuarioInfo usuarioInfo;
    private String nome_ficha, exercicios, peso, series;
    
    public TelaCriarFicha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        campoNomeFicha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoExercicios = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoPeso = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoRepeticao = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 74, 173));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1270, 680, 90, 30);

        campoNomeFicha.setBackground(new java.awt.Color(0, 74, 173));
        campoNomeFicha.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        campoNomeFicha.setForeground(new java.awt.Color(255, 255, 255));
        campoNomeFicha.setBorder(null);
        campoNomeFicha.setOpaque(true);
        campoNomeFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeFichaActionPerformed(evt);
            }
        });
        campoNomeFicha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNomeFichaKeyPressed(evt);
            }
        });
        jPanel1.add(campoNomeFicha);
        campoNomeFicha.setBounds(1010, 30, 340, 50);

        campoExercicios.setColumns(20);
        campoExercicios.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        campoExercicios.setRows(5);
        jScrollPane1.setViewportView(campoExercicios);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 670, 530);

        campoPeso.setColumns(20);
        campoPeso.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        campoPeso.setRows(5);
        jScrollPane2.setViewportView(campoPeso);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(700, 190, 270, 530);

        campoRepeticao.setColumns(20);
        campoRepeticao.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        campoRepeticao.setRows(5);
        jScrollPane3.setViewportView(campoRepeticao);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(1000, 190, 350, 480);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/FAzer login (3).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 720);

        jMenuBar1.setForeground(new java.awt.Color(0, 0, 102));

        jMenu1.setBackground(new java.awt.Color(0, 0, 204));
        jMenu1.setForeground(new java.awt.Color(0, 0, 153));
        jMenu1.setText("Ver modelo de ficha");

        jMenuItem1.setText("MODELO FICHA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 102));
        jMenu2.setText("Voltar tela perfil");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    
    modelo = new TelaModelo();
    modelo.setVisible(true);
    modelo.setExtendedState(modelo.MAXIMIZED_BOTH);
    this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void campoNomeFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeFichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeFichaActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
    
    int userId = UsuarioSession.getUserId();
    System.out.println("userId: " + userId);  // Verifique o valor de userId antes de buscar no banco
    InfoAcesso infoAcesso = new InfoAcesso();
    UsuarioInfo usuarioInfo = infoAcesso.getUsuarioInfo(userId);
    
        System.out.println("usuarioInfo: " + usuarioInfo);  // Para verificar se está null

        if (usuarioInfo != null) {
        perfil = new TelaPerfil(usuarioInfo);  // Agora, usuarioInfo não é null
        perfil.setExtendedState(perfil.MAXIMIZED_BOTH);
        perfil.setLocationRelativeTo(null);
        perfil.setVisible(true);
        this.dispose();
    } else {
        System.out.println("Erro: usuarioInfo está null");
        // Aqui você pode tratar a situação, como exibir uma mensagem de erro para o usuário.
    }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      nome_ficha = campoNomeFicha.getText();
      exercicios = campoExercicios.getText();
      peso = campoPeso.getText();
      series = campoRepeticao.getText();
      
      if (nome_ficha.isEmpty()) {
        JOptionPane.showMessageDialog(null, "O campo nome ficha é obrigátorio.", "Erro", JOptionPane.ERROR_MESSAGE);
        return; // Interrompe a execução caso algum campo esteja vazio
    }
      
      Ficha ficha = new Ficha(nome_ficha,exercicios,peso,series);
      CadastrarInformacoes info = new CadastrarInformacoes();
      UsuarioSession mandaId = new UsuarioSession();
      
      if (info.criarFicha(ficha, mandaId)) { // Agora não precisa passar usuarioId
    JOptionPane.showMessageDialog(null, "Ficha cadastrada com sucesso!!!", "Ficha", JOptionPane.INFORMATION_MESSAGE);
        int userId = UsuarioSession.getUserId();
    System.out.println("userId: " + userId);  // Verifique o valor de userId antes de buscar no banco
    InfoAcesso infoAcesso = new InfoAcesso();
    UsuarioInfo usuarioInfo = infoAcesso.getUsuarioInfo(userId);
    
        System.out.println("usuarioInfo: " + usuarioInfo);  // Para verificar se está null

        if (usuarioInfo != null) {
        perfil = new TelaPerfil(usuarioInfo);  // Agora, usuarioInfo não é null
        perfil.setExtendedState(perfil.MAXIMIZED_BOTH);
        perfil.setLocationRelativeTo(null);
        perfil.setVisible(true);
        this.dispose();
    } else {
        System.out.println("Erro: usuarioInfo está null");
        // Aqui você pode tratar a situação, como exibir uma mensagem de erro para o usuário.
    }
            
} else {
    JOptionPane.showMessageDialog(null, "Nome de ficha já registrado no seu perfil", "Erro", JOptionPane.ERROR_MESSAGE);
}

              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoNomeFichaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeFichaKeyPressed
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                campoExercicios.requestFocus(); // Foca no botão "Salvar"
            }
    }//GEN-LAST:event_campoNomeFichaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarFicha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea campoExercicios;
    private javax.swing.JTextField campoNomeFicha;
    private javax.swing.JTextArea campoPeso;
    private javax.swing.JTextArea campoRepeticao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
