/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dados.FichaInfo;
import dados.UsuarioInfo;
import dados.UsuarioSession;
import banco.InfoAcesso;
import dados.Ficha;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import banco.Acesso;

/**
 *
 * @author Pedro
 */
public class TelaFichaEditavel extends javax.swing.JFrame {

    private TelaPerfil perfil;
    private UsuarioInfo usuarioInfo;
    private TelaPesquisarFicha pesquisar;
    private int idFicha;
    /**
     * Creates new form TelaFichaEditavel
     */
    public TelaFichaEditavel(FichaInfo fichaInfo) {
        initComponents();
        campoNomeFicha.setText(fichaInfo.getNomeEcontrado());
        campoExercicicos.setText(fichaInfo.getExercicios());
        campoPeso.setText(fichaInfo.getPeso());
        campoSeries.setText(fichaInfo.getSeries());
        this.idFicha = fichaInfo.getId_ficha();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoExercicicos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoPeso = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoSeries = new javax.swing.JTextArea();
        campoNomeFicha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        voltaPerfil = new javax.swing.JMenuItem();
        voltaFicha = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        campoExercicicos.setColumns(20);
        campoExercicicos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        campoExercicicos.setRows(5);
        jScrollPane1.setViewportView(campoExercicicos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 190, 680, 530);

        campoPeso.setColumns(20);
        campoPeso.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        campoPeso.setRows(5);
        jScrollPane2.setViewportView(campoPeso);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(690, 190, 290, 530);

        campoSeries.setColumns(20);
        campoSeries.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        campoSeries.setRows(5);
        jScrollPane3.setViewportView(campoSeries);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(990, 190, 370, 530);

        campoNomeFicha.setBackground(new java.awt.Color(153, 204, 255));
        campoNomeFicha.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jPanel1.add(campoNomeFicha);
        campoNomeFicha.setBounds(890, 50, 450, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/FAzer login (7).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 720);

        jMenu1.setForeground(new java.awt.Color(0, 74, 173));
        jMenu1.setText("Voltar");

        voltaPerfil.setText("Voltar pra tela perfil");
        voltaPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaPerfilActionPerformed(evt);
            }
        });
        jMenu1.add(voltaPerfil);

        voltaFicha.setText("Voltar pra tela de fichas");
        voltaFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaFichaActionPerformed(evt);
            }
        });
        jMenu1.add(voltaFicha);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 74, 173));
        jMenu2.setText("Salvar Alterações");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1361, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltaPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaPerfilActionPerformed
        int userId = UsuarioSession.getUserId();
        System.out.println("userId: " + userId);  // Verifique o valor de userId antes de buscar no banco
        InfoAcesso infoAcesso = new InfoAcesso();
        UsuarioInfo usuarioInfo = infoAcesso.getUsuarioInfo(userId);

        System.out.println("usuarioInfo: " + usuarioInfo);  // Para verificar se está null

        if (usuarioInfo != null) {
            perfil = new TelaPerfil(usuarioInfo);  // Agora, usuarioInfo não é null
            perfil.setExtendedState(perfil.MAXIMIZED_BOTH);
            perfil.setLocationRelativeTo(null);
            perfil.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Erro: usuarioInfo está null");
            // Aqui você pode tratar a situação, como exibir uma mensagem de erro para o usuário.
        }
    }//GEN-LAST:event_voltaPerfilActionPerformed

    private void voltaFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaFichaActionPerformed
        InfoAcesso acesso = new InfoAcesso();
        UsuarioSession id = new UsuarioSession();
        List<String> nomesFichas = acesso.getNomesFichas(id); // Armazena o retorno do método em nomesFichas

        if (nomesFichas != null && !nomesFichas.isEmpty())
        {
            pesquisar = new TelaPesquisarFicha(nomesFichas);
            pesquisar.setVisible(true);
            pesquisar.setExtendedState(pesquisar.MAXIMIZED_BOTH);
            this.dispose();
            
        }
    }//GEN-LAST:event_voltaFichaActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
    
      String nome_ficha = campoNomeFicha.getText();
      String exercicios = campoExercicicos.getText();
      String peso = campoPeso.getText();
      String series = campoSeries.getText();
      
      
      Ficha ficha = new Ficha(nome_ficha,exercicios,peso,series);
      Acesso acesso = new Acesso();
      
      if (acesso.atualizarFicha(ficha, idFicha)) {
    JOptionPane.showMessageDialog(null, "Informações atualizadas com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    UsuarioSession id = new UsuarioSession();
    InfoAcesso infoAcesso = new InfoAcesso();
    
        List<String> nomesFichas = infoAcesso.getNomesFichas(id); // Armazena o retorno do método em nomesFichas

        if (nomesFichas != null && !nomesFichas.isEmpty())
        {
            pesquisar = new TelaPesquisarFicha(nomesFichas);
            pesquisar.setVisible(true);
            pesquisar.setExtendedState(pesquisar.MAXIMIZED_BOTH);
            this.dispose();
        }
        this.dispose();
         
} else {
    JOptionPane.showMessageDialog(null, "Erro ao atualizar as informações.", "Erro", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(TelaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(TelaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(TelaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(TelaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Simulação de FichaInfo para teste
            FichaInfo fichaInfo = new FichaInfo("Treino 1","Exercício A, Exercício B", "50kg, 60kg", "3x10, 4x12");
           
            new TelaFichaEditavel(fichaInfo).setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea campoExercicicos;
    private javax.swing.JTextField campoNomeFicha;
    private javax.swing.JTextArea campoPeso;
    private javax.swing.JTextArea campoSeries;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem voltaFicha;
    private javax.swing.JMenuItem voltaPerfil;
    // End of variables declaration//GEN-END:variables
}
