/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.List;
import java.util.Arrays;
import banco.InfoAcesso;
import dados.UsuarioSession;
import dados.FichaInfo;
import dados.UsuarioInfo;
import javax.swing.JOptionPane;





public class TelaPesquisarFicha extends javax.swing.JFrame {

    private String nomeFicha;
    private TelaFicha telaFicha;
    private TelaPerfil perfil;
    private UsuarioInfo usuarioInfo;
    private TelaProcurarFichasUsuarios procurar;
    private TelaDeletarFicha deletaFicha;
    private TelaEditaFicha edita;
     
    public TelaPesquisarFicha(List<String> nomesFichas) {
        initComponents();
        exibirNomesFichas(nomesFichas);
    }
    
    private void exibirNomesFichas(List<String> nomesFichas) {
        // Junta todos os nomes das fichas em uma única String, com cada nome em uma nova linha
        StringBuilder builder = new StringBuilder();
        for (String nome : nomesFichas) {
            builder.append(nome).append("\n");
        }
        campoMostrarFichas.setText(builder.toString()); // Define o texto do campo com os nomes formatados
        campoMostrarFichas.setEditable(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoMostrarFichas = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        campoNomeFicha = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 74, 173));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1160, 650, 110, 30);

        campoMostrarFichas.setColumns(20);
        campoMostrarFichas.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        campoMostrarFichas.setForeground(new java.awt.Color(0, 0, 153));
        campoMostrarFichas.setRows(5);
        jScrollPane1.setViewportView(campoMostrarFichas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 1120, 510);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Fichas Disponíveis");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 150, 287, 48);

        campoNomeFicha.setBackground(new java.awt.Color(0, 74, 173));
        campoNomeFicha.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        campoNomeFicha.setForeground(new java.awt.Color(255, 255, 255));
        campoNomeFicha.setBorder(null);
        campoNomeFicha.setOpaque(true);
        campoNomeFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeFichaActionPerformed(evt);
            }
        });
        campoNomeFicha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNomeFichaKeyPressed(evt);
            }
        });
        jPanel1.add(campoNomeFicha);
        campoNomeFicha.setBounds(930, 30, 420, 50);

        jButton2.setBackground(new java.awt.Color(0, 74, 173));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Excluir Ficha");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1160, 320, 120, 30);

        jButton3.setBackground(new java.awt.Color(0, 74, 173));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Editar Ficha");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1160, 370, 120, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/FAzer login (6).png"))); // NOI18N
        jLabel1.setText("Fichas Dispiníveis");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1364, 720);

        jMenu1.setForeground(new java.awt.Color(0, 74, 173));
        jMenu1.setText("Ver fichas de outros usuários");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 74, 173));
        jMenu2.setText("Voltar pra tela perfil");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeFichaActionPerformed
       
    }//GEN-LAST:event_campoNomeFichaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String nomeFicha = campoNomeFicha.getText();
    
    if (nomeFicha.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Insira o nome da ficha", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    InfoAcesso acesso = new InfoAcesso();
    UsuarioSession id = new UsuarioSession();

    FichaInfo fichaInfo = acesso.buscarFichaEspecifica(id, nomeFicha); 

    if (fichaInfo != null) {

        telaFicha = new TelaFicha(fichaInfo);
        telaFicha.setVisible(true);
        telaFicha.setExtendedState(telaFicha.MAXIMIZED_BOTH);
        this.dispose();

    } else {
        campoMostrarFichas.setText("Ficha não encontrada.");
    }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
    int userId = UsuarioSession.getUserId();
    System.out.println("userId: " + userId);  // Verifique o valor de userId antes de buscar no banco
    InfoAcesso infoAcesso = new InfoAcesso();
    UsuarioInfo usuarioInfo = infoAcesso.getUsuarioInfo(userId);
    
        System.out.println("usuarioInfo: " + usuarioInfo);  // Para verificar se está null

        if (usuarioInfo != null) {
        perfil = new TelaPerfil(usuarioInfo);  // Agora, usuarioInfo não é null
        perfil.setExtendedState(perfil.MAXIMIZED_BOTH);
        perfil.setLocationRelativeTo(null);
        perfil.setVisible(true);
        this.dispose();
    } else {
        System.out.println("Erro: usuarioInfo está null");
        // Aqui você pode tratar a situação, como exibir uma mensagem de erro para o usuário.
    }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
      if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.doClick(); // Executa o botão "Salvar"
            }  
    }//GEN-LAST:event_jButton1KeyPressed

    private void campoNomeFichaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeFichaKeyPressed
       if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.doClick(); // Executa o botão "Salvar"
            }  
    }//GEN-LAST:event_campoNomeFichaKeyPressed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
          procurar = new TelaProcurarFichasUsuarios();
          procurar.setVisible(true);
          procurar.setExtendedState(procurar.MAXIMIZED_BOTH);  
          this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      deletaFicha = new TelaDeletarFicha();
      deletaFicha.setVisible(true);
      deletaFicha.setExtendedState(deletaFicha.MAXIMIZED_BOTH);
      this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       edita = new TelaEditaFicha();
       edita.setVisible(true);
       edita.setExtendedState(edita.MAXIMIZED_BOTH);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(TelaPesquisarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(TelaPesquisarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(TelaPesquisarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(TelaPesquisarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Lista de exemplo de nomes de fichas
            List<String> nomesFichas = Arrays.asList("Ficha 1", "Ficha 2", "Ficha 3");

            // Passa a lista para o construtor
            new TelaPesquisarFicha(nomesFichas).setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea campoMostrarFichas;
    private javax.swing.JTextField campoNomeFicha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
