/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dados.InfosCadastro;
import banco.CadastrarInformacoes;
import javax.swing.JOptionPane;

public class TelaInfo extends javax.swing.JFrame {

    private String nome,idade,telefone,academia;
    private  TelaLogin login;
    private int usuarioId;
    
    public TelaInfo(int usuarioId) { // Modificando o construtor para receber o ID
        initComponents();
        this.usuarioId = usuarioId; // Armazenando o ID recebido
        }

    public TelaInfo() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoIdade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        campoTelefone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoAcademia = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Telefone");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(570, 400, 120, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Nome");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(600, 200, 120, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Idade");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(590, 300, 120, 50);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Academia");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 500, 160, 50);

        campoIdade.setBackground(new java.awt.Color(204, 204, 204));
        campoIdade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoIdadeKeyPressed(evt);
            }
        });
        jPanel1.add(campoIdade);
        campoIdade.setBounds(690, 350, 570, 60);

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1230, 650, 100, 40);

        campoTelefone.setBackground(new java.awt.Color(204, 204, 204));
        campoTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoTelefoneKeyPressed(evt);
            }
        });
        jPanel1.add(campoTelefone);
        campoTelefone.setBounds(690, 450, 570, 60);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Fechar");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1860, 990, 120, 20);

        campoAcademia.setBackground(new java.awt.Color(204, 204, 204));
        campoAcademia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoAcademia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoAcademiaKeyPressed(evt);
            }
        });
        jPanel1.add(campoAcademia);
        campoAcademia.setBounds(690, 550, 570, 60);

        campoNome.setBackground(new java.awt.Color(204, 204, 204));
        campoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNomeKeyPressed(evt);
            }
        });
        jPanel1.add(campoNome);
        campoNome.setBounds(690, 250, 570, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/CADASTRO (4).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1670, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1366, 977);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nome = campoNome.getText();
        idade = campoIdade.getText();
        telefone = campoTelefone.getText();
        academia = campoAcademia.getText();
        
        if (nome.isEmpty() || idade.isEmpty() || telefone.isEmpty() || academia.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.", "Erro", JOptionPane.ERROR_MESSAGE);
        return; // Interrompe a execução caso algum campo esteja vazio
    }
        try {
        int idadeNum = Integer.parseInt(idade);
        if (idadeNum <= 0) {
            JOptionPane.showMessageDialog(null, "A idade deve ser um número positivo.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "A idade deve ser um número válido.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Verificação de telefone numérico
    if (!telefone.matches("\\(\\d{2}\\) \\d{5}-\\d{4}")) {
        JOptionPane.showMessageDialog(null, "O telefone deve estar no formato (ddd) 12345-1234.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

        // Criando objeto Infos com o ID do usuário
        InfosCadastro infos = new InfosCadastro(usuarioId, nome, idade, telefone, academia); 
        CadastrarInformacoes info = new CadastrarInformacoes();

        // Verificando se os dados foram inseridos corretamente
        if (info.inserirDados(infos)) { // Agora não precisa passar usuarioId
    JOptionPane.showMessageDialog(null, "Informações cadastradas com sucesso!!!", "Perfil", JOptionPane.INFORMATION_MESSAGE);
            login = new TelaLogin();
            login.setExtendedState(login.MAXIMIZED_BOTH);
            login.setLocationRelativeTo(null);
            login.setVisible(true);
            this.dispose();
} else {
    JOptionPane.showMessageDialog(null, "Erro no cadastro", "Erro", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void campoNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeKeyPressed
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                campoIdade.requestFocus(); // Foca no próximo campo
            }
    }//GEN-LAST:event_campoNomeKeyPressed

    private void campoIdadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIdadeKeyPressed
      if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                campoTelefone.requestFocus(); // Foca no próximo campo
            }
    }//GEN-LAST:event_campoIdadeKeyPressed

    private void campoTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTelefoneKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                campoAcademia.requestFocus(); // Foca no próximo campo
            }
    }//GEN-LAST:event_campoTelefoneKeyPressed

    private void campoAcademiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAcademiaKeyPressed
      if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.requestFocus(); // Foca no botão "Salvar"
            }
   
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.doClick(); // Executa o botão "Salvar"
            }
    }//GEN-LAST:event_campoAcademiaKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.doClick(); // Executa o botão "Salvar"
            }
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Exemplo de ID do usuário. Você deve obter esse ID de alguma forma, como a partir do login. */
        int usuarioId = 1; // Coloque aqui o ID real do usuário que você deseja passar

        // Create and display the form
        java.awt.EventQueue.invokeLater(() -> {
            new TelaInfo(usuarioId).setVisible(true); // Passando o ID para o construtor
        });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoAcademia;
    private javax.swing.JTextField campoIdade;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
