/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import banco.Cadastrar;
import dados.Criar;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    private String cemail, csenha, crepete;
    private TelaInfo info;
    private TelaLogin login;
    
    public TelaCadastro() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cadastroEmail = new javax.swing.JTextField();
        cadastroSenha = new javax.swing.JTextField();
        cadastroRepetir = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(600, 380, 110, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Repetir senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 500, 170, 32);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 260, 120, 30);

        cadastroEmail.setBackground(new java.awt.Color(204, 204, 204));
        cadastroEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastroEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroEmailActionPerformed(evt);
            }
        });
        cadastroEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroEmailKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroEmail);
        cadastroEmail.setBounds(600, 300, 460, 60);

        cadastroSenha.setBackground(new java.awt.Color(204, 204, 204));
        cadastroSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastroSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroSenhaActionPerformed(evt);
            }
        });
        cadastroSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroSenha);
        cadastroSenha.setBounds(600, 420, 460, 60);

        cadastroRepetir.setBackground(new java.awt.Color(204, 204, 204));
        cadastroRepetir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastroRepetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroRepetirActionPerformed(evt);
            }
        });
        cadastroRepetir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroRepetirKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroRepetir);
        cadastroRepetir.setBounds(600, 540, 460, 60);

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1090, 560, 120, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Voltar para o Login");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1190, 680, 170, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Voltar");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1840, 960, 60, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/CADASTRO (2).png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1370, 720);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroEmailActionPerformed

    private void cadastroRepetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroRepetirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroRepetirActionPerformed

    private void cadastroSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroSenhaActionPerformed

    private boolean isEmailValid(String email) {
    String emailPattern = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$";
    return email.matches(emailPattern);
}// validar email
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    cemail = cadastroEmail.getText();
    csenha = cadastroSenha.getText();
    crepete = cadastroRepetir.getText();
    
    if (cemail.trim().isEmpty() || csenha.trim().isEmpty() || crepete.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.", "Erro", JOptionPane.ERROR_MESSAGE);
        return; // Interrompe a execução para impedir o cadastro
    }
    
    if (!isEmailValid(cemail)) {
        JOptionPane.showMessageDialog(null, "Por favor, insira um endereço de e-mail válido.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
    

       if (csenha.equals(crepete)) {
        Criar criar = new Criar(cemail, csenha); 
        Cadastrar cadastro = new Cadastrar();
        
        criar.setCemail(cemail);
        criar.setCsenha(csenha);
        
        // Chama o método inserirDados e armazena o resultado
        int userId = cadastro.inserirDados(criar); // Armazena o ID do usuário aqui

        // Verificando o resultado da inserção
        if (userId > 0) { // Se o ID gerado for maior que 0, o cadastro foi bem-sucedido
            JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!" , "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            
            // Agora use o userId aqui
            info = new TelaInfo(userId); // Passa o userId para o construtor de TelaInfo
            info.setExtendedState(info.MAXIMIZED_BOTH);
            info.setLocationRelativeTo(null);
            info.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar usuário.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Senhas diferentes", "Erro", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    
    }//GEN-LAST:event_jLabel5MouseClicked

    private void cadastroEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroEmailKeyPressed
     if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                cadastroSenha.requestFocus(); // Foca no próximo campo
            }
    }//GEN-LAST:event_cadastroEmailKeyPressed

    private void cadastroSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroSenhaKeyPressed
     if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                cadastroRepetir.requestFocus(); // Foca no próximo campo
            }
    }//GEN-LAST:event_cadastroSenhaKeyPressed

    private void cadastroRepetirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroRepetirKeyPressed
       if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.requestFocus(); // Foca no botão "Salvar"
            }
   
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.doClick(); // Executa o botão "Salvar"
            }
    }//GEN-LAST:event_cadastroRepetirKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
       if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.doClick(); // Executa o botão "Salvar"
            }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
           this.dispose();
           login = new TelaLogin();
           login.setVisible(true);
           login.setExtendedState(login.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cadastroEmail;
    private javax.swing.JTextField cadastroRepetir;
    private javax.swing.JTextField cadastroSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
