/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import banco.Cadastrar;
import dados.UsuarioInfo;
import banco.InfoAcesso;
import dados.UsuarioSession;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;



public class TelaPerfil extends javax.swing.JFrame {

   
private TelaLogin login;
private TelaDeletar deleta;
private TelaAlterarInfos altera;
private TelaCriarFicha ficha;
private TelaPesquisarFicha pesquisar;
private TelaSenha senha;
private TelaUsuarios usuario;
private TelaProcurarFichasUsuarios outros;
    
public TelaPerfil(UsuarioInfo usuario) {
    initComponents();
    System.out.println("Exibindo dados do usuário: " + usuario.getNome());
    
    // Definindo os campos de perfil com os dados do usuário
    perfilNome.setText(usuario.getNome());
    perfilIdade.setText(usuario.getIdade());
    perfilTelefone.setText(usuario.getTelefone());
    perfilAcademia.setText(usuario.getAcademia());
}

    

    
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        perfilIdade = new javax.swing.JLabel();
        perfilTelefone = new javax.swing.JLabel();
        perfilAcademia = new javax.swing.JLabel();
        perfilNome = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        alteraPerfil = new javax.swing.JMenuItem();
        alteraSenha = new javax.swing.JMenuItem();
        excluiConta = new javax.swing.JMenuItem();
        visualizaPerfil = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        perfilIdade.setFont(new java.awt.Font("Square721 BT", 0, 32)); // NOI18N
        perfilIdade.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(perfilIdade);
        perfilIdade.setBounds(610, 230, 230, 40);

        perfilTelefone.setFont(new java.awt.Font("Square721 BT", 0, 32)); // NOI18N
        perfilTelefone.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(perfilTelefone);
        perfilTelefone.setBounds(650, 300, 660, 30);

        perfilAcademia.setFont(new java.awt.Font("Square721 BT", 0, 32)); // NOI18N
        perfilAcademia.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(perfilAcademia);
        perfilAcademia.setBounds(670, 360, 630, 40);

        perfilNome.setFont(new java.awt.Font("Square721 BT", 0, 32)); // NOI18N
        perfilNome.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(perfilNome);
        perfilNome.setBounds(620, 160, 660, 40);

        jButton1.setBackground(new java.awt.Color(0, 74, 173));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Criar ficha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(990, 600, 120, 32);

        jButton2.setBackground(new java.awt.Color(0, 74, 173));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Visualizar fichas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1140, 600, 180, 32);

        jButton3.setBackground(new java.awt.Color(0, 74, 173));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ver ficha de outros usuários");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1010, 650, 260, 32);

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/FAzer login (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 710);

        jMenu1.setForeground(new java.awt.Color(0, 74, 173));
        jMenu1.setText("Opções");

        alteraPerfil.setText("Alterar informações do perfil");
        alteraPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraPerfilActionPerformed(evt);
            }
        });
        jMenu1.add(alteraPerfil);

        alteraSenha.setText("Alterar senha");
        alteraSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraSenhaActionPerformed(evt);
            }
        });
        jMenu1.add(alteraSenha);

        excluiConta.setText("Excluir conta");
        excluiConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluiContaMouseClicked(evt);
            }
        });
        excluiConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluiContaActionPerformed(evt);
            }
        });
        jMenu1.add(excluiConta);

        visualizaPerfil.setText("Visualizar outros usuarios");
        visualizaPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizaPerfilActionPerformed(evt);
            }
        });
        jMenu1.add(visualizaPerfil);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 74, 173));
        jMenu2.setText("Desconectar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2054, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alteraPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraPerfilActionPerformed
       this.dispose();
      altera = new TelaAlterarInfos();
      altera.setVisible(true);
      altera.setExtendedState(altera.MAXIMIZED_BOTH);
    }//GEN-LAST:event_alteraPerfilActionPerformed

    private void alteraSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraSenhaActionPerformed
      this.dispose();
      senha = new TelaSenha();
      senha.setVisible(true);
      senha.setExtendedState(senha.MAXIMIZED_BOTH);
    }//GEN-LAST:event_alteraSenhaActionPerformed

    private void visualizaPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizaPerfilActionPerformed
      this.dispose();
      usuario = new TelaUsuarios();
      usuario.setVisible(true);
      usuario.setExtendedState(usuario.MAXIMIZED_BOTH);
    }//GEN-LAST:event_visualizaPerfilActionPerformed

    private void excluiContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluiContaActionPerformed
      this.dispose();
      deleta = new TelaDeletar();
      deleta.setVisible(true);
      deleta.setExtendedState(deleta.MAXIMIZED_BOTH);
      
    }//GEN-LAST:event_excluiContaActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
      dispose();
      login = new TelaLogin();
      login.setVisible(true);
      login.setExtendedState(login.MAXIMIZED_BOTH);
     
    }//GEN-LAST:event_jMenu2MouseClicked

    private void excluiContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluiContaMouseClicked
      
    }//GEN-LAST:event_excluiContaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         InfoAcesso acesso = new InfoAcesso();
         UsuarioSession id = new UsuarioSession();
         List<String> nomesFichas = acesso.getNomesFichas(id); // Armazena o retorno do método em nomesFichas

        if (nomesFichas != null && !nomesFichas.isEmpty())
        { 
          pesquisar = new TelaPesquisarFicha(nomesFichas);
          pesquisar.setVisible(true);
          pesquisar.setExtendedState(pesquisar.MAXIMIZED_BOTH);
          this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nenhuma ficha cadastrada", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      ficha = new TelaCriarFicha();
      ficha.setVisible(true);
      ficha.setExtendedState(ficha.MAXIMIZED_BOTH);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     outros = new TelaProcurarFichasUsuarios();
     outros.setVisible(true);
     outros.setExtendedState(outros.MAXIMIZED_BOTH);
     this.dispose();
     
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    // Criando um exemplo de UsuarioInfo
    UsuarioInfo usuario = new UsuarioInfo();
    usuario.setNome("João");
    usuario.setIdade("25");
    usuario.setTelefone("123456789");
    usuario.setAcademia("Academia X");

    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // Criando e exibindo a tela passando o objeto usuario
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new TelaPerfil(usuario).setVisible(true);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alteraPerfil;
    private javax.swing.JMenuItem alteraSenha;
    private javax.swing.JMenuItem excluiConta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel perfilAcademia;
    private javax.swing.JLabel perfilIdade;
    private javax.swing.JLabel perfilNome;
    private javax.swing.JLabel perfilTelefone;
    private javax.swing.JMenuItem visualizaPerfil;
    // End of variables declaration//GEN-END:variables
}
