/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import banco.Acesso;
import dados.Login;
import javax.swing.JOptionPane;
import dados.UsuarioInfo;
import dados.UsuarioSession;
import banco.InfoAcesso;

/**
 *
 * @author Pedro
 */
public class TelaDeletar extends javax.swing.JFrame {

    private String delete;
    private String delemail;
    private TelaLogin login;
    private TelaPerfil perfil;
    private UsuarioInfo usuario;
    
    public TelaDeletar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        deletaEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deletaSenha = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Insira o email ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 390, 370, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(680, 560, 130, 40);

        deletaEmail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        deletaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletaEmailActionPerformed(evt);
            }
        });
        deletaEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deletaEmailKeyPressed(evt);
            }
        });
        jPanel1.add(deletaEmail);
        deletaEmail.setBounds(520, 420, 430, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Deletar conta");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(520, 560, 150, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Insira a senha ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 460, 370, 30);

        deletaSenha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        deletaSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deletaSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(deletaSenha);
        deletaSenha.setBounds(520, 500, 430, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/olhoo.png"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(960, 510, 60, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Voltar para o Perfil");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1190, 690, 170, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/FAzer login (2)_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isEmailValid(String email) {
    String emailPattern = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$";
    return email.matches(emailPattern);
}// validar email
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
delemail = deletaEmail.getText();
delete = deletaSenha.getText();
Acesso acesso = new Acesso();
Login acessoLogin = new Login();
if (delemail.isEmpty() || delete.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.", "Erro", JOptionPane.ERROR_MESSAGE);
        return; // Interrompe a execução caso algum campo esteja vazio
    }

if (!isEmailValid(delemail)) {
        JOptionPane.showMessageDialog(null, "Por favor, insira um endereço de e-mail válido.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

acessoLogin.setEmail(delemail);
acessoLogin.setSenha(delete);

if(acesso.verificaAcesso(acessoLogin) != null) {
    Object[] options = {"Sim", "Não"};
    int resposta = JOptionPane.showOptionDialog(
        null, 
        "Deseja continuar?", 
        "Confirmação", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE, 
        null, 
        options, 
        options[0]
            
    );

    if (resposta == JOptionPane.YES_OPTION) {
        if(acesso.excluirConta(delemail, delete)) {
            System.out.println("Usuário escolheu Sim.");
            JOptionPane.showMessageDialog(null, "Conta excluída com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

            TelaLogin login = new TelaLogin();
            login.setVisible(true);
            login.setExtendedState(login.MAXIMIZED_BOTH);
        } else {
            System.out.println("Erro ao deletar conta");
            JOptionPane.showMessageDialog(null, "Erro ao deletar conta", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } else if (resposta == JOptionPane.NO_OPTION) {
        System.out.println("Usuário escolheu Não.");
        deletaEmail.setText("");
        deletaSenha.setText("");
    } else {
        System.out.println("Usuário fechou a caixa de diálogo.");
    }
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void deletaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletaEmailActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
           int userId = UsuarioSession.getUserId();
    System.out.println("userId: " + userId);  // Verifique o valor de userId antes de buscar no banco
    InfoAcesso infoAcesso = new InfoAcesso();
    UsuarioInfo usuarioInfo = infoAcesso.getUsuarioInfo(userId);
    
        System.out.println("usuarioInfo: " + usuarioInfo);  // Para verificar se está null

        if (usuarioInfo != null) {
        perfil = new TelaPerfil(usuarioInfo);  // Agora, usuarioInfo não é null
        perfil.setExtendedState(perfil.MAXIMIZED_BOTH);
        perfil.setLocationRelativeTo(null);
        perfil.setVisible(true);
        this.dispose();
    } else {
        System.out.println("Erro: usuarioInfo está null");
        // Aqui você pode tratar a situação, como exibir uma mensagem de erro para o usuário.
    }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void deletaEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deletaEmailKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                deletaSenha.requestFocus(); // Foca no próximo campo
            }
    }//GEN-LAST:event_deletaEmailKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
       if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.doClick(); // Executa o botão "Salvar"
            }
    }//GEN-LAST:event_jButton1KeyPressed

    private boolean senhaVisivel = false;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if (senhaVisivel) {
            deletaSenha.setEchoChar('*'); // Oculta a senha
        } else {
            deletaSenha.setEchoChar((char) 0); // Exibe a senha
        }
        senhaVisivel = !senhaVisivel;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deletaSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deletaSenhaKeyPressed
     if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.requestFocus(); // Foca no botão "Salvar"
            }
   
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.doClick(); // Executa o botão "Salvar"
            }  
    }//GEN-LAST:event_deletaSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeletar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeletar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeletar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeletar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeletar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deletaEmail;
    private javax.swing.JPasswordField deletaSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
