/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dados.UsuarioInfo;
import dados.InfosAtualizar;
import dados.Id;
import banco.CadastrarInformacoes;
import javax.swing.JOptionPane;
import banco.Acesso;
import banco.InfoAcesso;

/**
 *
 * @author aluno
 */
public class TelaEditaInfo extends javax.swing.JFrame {
    
    private int usuarioId;
    private String nome, idade, telefone, academia;
    private int id;
    private TelaPerfil perfil;
    
    
    public TelaEditaInfo(UsuarioInfo usuario) {
    initComponents(); // Inicializa os componentes antes de usá-los
    System.out.println("Exibindo dados do usuário: " + usuario.getNome());
    
    // Definindo os campos de perfil com os dados do usuário
    campoNome.setText(usuario.getNome());
    campoIdade.setText(usuario.getIdade());
    campoTelefone.setText(usuario.getTelefone());
    campoAcademia.setText(usuario.getAcademia());
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoAcademia = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoIdade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        campoNome.setBackground(new java.awt.Color(204, 204, 204));
        campoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNomeKeyPressed(evt);
            }
        });
        jPanel1.add(campoNome);
        campoNome.setBounds(620, 300, 570, 60);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Nome");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(530, 250, 120, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Idade");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(520, 350, 120, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Telefone");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(500, 450, 120, 50);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Academia");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(490, 550, 160, 50);

        campoAcademia.setBackground(new java.awt.Color(204, 204, 204));
        campoAcademia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoAcademia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoAcademiaKeyPressed(evt);
            }
        });
        jPanel1.add(campoAcademia);
        campoAcademia.setBounds(620, 600, 570, 60);

        campoTelefone.setBackground(new java.awt.Color(204, 204, 204));
        campoTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoTelefoneKeyPressed(evt);
            }
        });
        jPanel1.add(campoTelefone);
        campoTelefone.setBounds(620, 500, 570, 60);

        campoIdade.setBackground(new java.awt.Color(204, 204, 204));
        campoIdade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoIdadeKeyPressed(evt);
            }
        });
        jPanel1.add(campoIdade);
        campoIdade.setBounds(620, 400, 570, 60);

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1220, 620, 120, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/'.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(470, 10, 890, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/Alterar.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1449, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            campoIdade.requestFocus(); // Foca no próximo campo
        }
    }//GEN-LAST:event_campoNomeKeyPressed

    private void campoAcademiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAcademiaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            jButton1.requestFocus(); // Foca no botão "Salvar"
        }

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            jButton1.doClick(); // Executa o botão "Salvar"
        }
    }//GEN-LAST:event_campoAcademiaKeyPressed

    private void campoTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTelefoneKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            campoAcademia.requestFocus(); // Foca no próximo campo
        }
    }//GEN-LAST:event_campoTelefoneKeyPressed

    private void campoIdadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIdadeKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            campoTelefone.requestFocus(); // Foca no próximo campo
        }
    }//GEN-LAST:event_campoIdadeKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nome = campoNome.getText();
        idade = campoIdade.getText();
        telefone = campoTelefone.getText();
        academia = campoAcademia.getText();
        
        Acesso acesso = new Acesso();

        if (nome.isEmpty() || idade.isEmpty() || telefone.isEmpty() || academia.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.", "Erro", JOptionPane.ERROR_MESSAGE);
            return; // Interrompe se algum campo estiver vazio
        }
        if (!telefone.matches("\\(\\d{2}\\) \\d{5}-\\d{4}")) {
        JOptionPane.showMessageDialog(null, "O telefone deve estar no formato (ddd) 12345-1234.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

        // Criando objeto InfosCadastro com as informações atualizadas
        InfosAtualizar infos = new InfosAtualizar(nome, idade, telefone, academia);
        Id pegaId = new Id();
 
        System.out.println("teste id-"+id);
        // Atualizando os dados do usuário no banco de dados
        if (acesso.atualizarDados(infos, id)) {
    JOptionPane.showMessageDialog(null, "Informações atualizadas com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    this.dispose();
        InfoAcesso infoAcesso = new InfoAcesso();
        UsuarioInfo usuarioInfo = infoAcesso.getUsuarioInfo(id); 
        perfil = new TelaPerfil(usuarioInfo);
        perfil.setExtendedState(perfil.MAXIMIZED_BOTH);
        perfil.setLocationRelativeTo(null);
        perfil.setVisible(true);
         
} else {
    JOptionPane.showMessageDialog(null, "Erro ao atualizar as informações.", "Erro", JOptionPane.ERROR_MESSAGE);
}

   
    }//GEN-LAST:event_jButton1ActionPerformed
    public void recebeId(int id)
    {
        this.id = id;
        System.out.println("teste id-"+id);
    }
    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            jButton1.doClick(); // Executa o botão "Salvar"
        }
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    UsuarioInfo usuario = new UsuarioInfo();
    usuario.setNome("João");
    usuario.setIdade("25");
    usuario.setTelefone("123456789");
    usuario.setAcademia("Academia X");

    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // Criando e exibindo a tela passando o objeto usuario
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new TelaEditaInfo(usuario).setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoAcademia;
    private javax.swing.JTextField campoIdade;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
